# ADD BESTSELLER COLUMN
ALTER TABLE BOOKS ADD BESTSELLER BOOLEAN DEFAULT 0;
SELECT * FROM BOOKS;

# CREATE UPDATE BESTSELLER PROCEDURE
DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE BK_ID, RENTS_COUNT INT;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE IS_BESTSELLER BOOLEAN DEFAULT FALSE;
    DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM RENTS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    OPEN ALL_BOOKS;

    WHILE (FINISHED = 0) DO
        FETCH ALL_BOOKS INTO BK_ID;
        IF (FINISHED = 0) THEN
            SELECT COUNT(*) FROM RENTS
            WHERE BOOK_ID = BK_ID
            INTO RENTS_COUNT;

            IF (RENTS_COUNT > 2) THEN
                SET IS_BESTSELLER = TRUE;
            END IF;

            UPDATE BOOKS SET BESTSELLER = IS_BESTSELLER
            WHERE BOOK_ID = BK_ID;
            COMMIT;
        END IF;
    END WHILE;
    CLOSE ALL_BOOKS;
END $$

DELIMITER ;

CALL UpdateBestsellers();
SELECT * FROM RENTS;
SELECT * FROM BOOKS;